name: avosdroits
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  http: ^1.1.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_markdown: ^0.6.18
  file_picker: ^6.1.1
  path_provider: ^2.1.2
  dio: ^5.4.0
  syncfusion_flutter_pdfviewer: ^28.1.41
  photo_view: ^0.15.0
  image_picker: ^1.0.7
  google_maps_flutter: ^2.5.3
  geolocator: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
